### ISSUE TITLE
Incompatibility with Immersive Portals

### ISSUE THREAD

**Issue by srnyx** [Hephaestus-Dev/FibLib#11]
https://github.com/qouteall/ImmersivePortalsMod/issues/616

**Comment by qouteall** [comment]
The conflict is here https://github.com/Hephaestus-Dev/FibLib/blob/1.16/src/main/java/dev/hephaestus/fiblib/mixin/packets/chunkdata/MixinThreadedAnvilChunkStorage.java

The method `sendChunkDataPackets` will be invoked every time a chunk is sent to player. I think that injecting `sendChunkDataPackets`'s head is also fine

**Comment by Haven-King** [comment]
An injection at head will not fire if the method is overwritten. I think the easiest solution is for me to just mixin to your `ChunkDataSyncManager#sendChunkDataPacketNow` instead of TACS when IP is present.

**Comment by srnyx** [comment]
ETA on this being fixed?

**Comment by srnyx** [comment]
Can this be fixed today?
My server is unable to start because of this, and my players are not happy.

**Comment by Haven-King** [comment]
This has been fixed. The new version of SAX can be found [here](https://modrinth.com/mod/sax/version/bEQMJEjP).

**Comment by srnyx** [comment]
> This has been fixed. The new version of SAX can be found [here](https://modrinth.com/mod/sax/version/bEQMJEjP).

Thank you so much dude, you're a lifesaver.

**Comment by qouteall** [comment]
@Haven-King The overwritten method can be injected. You just need to make its priority lower such as 900
