### ISSUE TITLE
I made some better docs

### ISSUE THREAD

**Issue by skyfallwastaken** [Hephaestus-Dev/FibLib#16]
Seems the dev is inactive, I made a new repo that has better docs (including Kotlin code examples) and a nicer Readme. There'll soon be an example mod too! **https://github.com/SkyfallWasTaken/FibLib**

**Comment by Draylar** [comment]
Just a heads up that I also plan to [maintain a fork of FibLib](https://github.com/Draylar/FibLib) for [Game Phases](https://github.com/Draylar/game-phases) & another new project I am going to release in the next month. If you (or anyone else) end up releasing a 1.17 project that also depends on FibLib, or you would like to collaborate on documentation / features, please let me know so we can avoid conflicting with duplicate forks.

I plan to expand the scope of the library, namely by faking delta, drops, and other block properties on the server to allow the library to be used for more realistic block disguises. I have already implemented the first and second examples.

\* *I would be happy to PR my changes to this upstream repo if needed - just keeping everything in my fork for now so it is easier to push releases from & maintain. Haven, if you want me to PR to give you control of the library at any point, please let me know.*

**Comment by skyfallwastaken** [comment]
That's neat!

**Comment by Haven-King** [comment]
Sorry for the late reply. I would be happy to make either or both of you maintainers of this repository.

**Comment by Draylar** [comment]
That would be fantastic, I'm game for being a maintainer on this upstream repository if you are fine with it.

While I have you, would you mind clarifying which license you would like the project to be under? README says MIT, LICENSE is CC0 (which I also accidentally do all the time... haha). I licensed my fork under MIT, but wanted to check if you have any preference before committing to it.

**Comment by skyfallwastaken** [comment]
I'd be cool with being a maintainer too!

Also @Draylar I assume MIT because he probably decided to modify the readme to say that it's licensed under MIT but forgot to change the LICENSE file.

**Comment by Haven-King** [comment]
Great, I've invited both of you. I'll try and add an action to publish builds to my Maven repository soon to save any headaches in that department. Feel free to implement your changes to both the repository itself and the wiki directly.
