### ISSUE TITLE
Add Entity Fibbing

### ISSUE THREAD

**Issue by Haven-King** [Hephaestus-Dev/FibLib#2]
This is something I'd like to add soon. Shouldn't be too difficult, I just haven't gotten around to it.

**Comment by Frontrider** [comment]
This one needs to be very granular.

A little off, but in another project of mine, I was thinking about how to fake modded blocks to vanilla clients, and you could use the combination of a barrier (invisible, has a hitbox) and an invisible armor stand wearing an item with a custom model (enlarged, etc), provided by the server's resource pack, if replacing it with a vanilla block is not feasible (eg, your custom machine).
For entities, you could just do some "billboarding".
