### ISSUE TITLE
CurseForge upload? (1.18.2 File missing)

### ISSUE THREAD

**Issue by MSandro** [Hephaestus-Dev/FibLib#24]
Hello. I can't find FibLib on CurseForge.
I would greatly appreciate it if you could make it available there. Other mods (e.g. Game Phases) that are there are based on your mod but cannot be used in modpacks because FibLib is not available. Too bad.

**Comment by Haven-King** [comment]
@Draylar feel free to create a project on CurseForge for this if you'd like.

**Comment by 0gp** [comment]
Any news here?
I would really appreciate it if the mod would be available on CurseForge soon.

**Comment by Draylar** [comment]
Done & done - Haven, I added you to the project with full permissions and 100% points (sit back and relax as I get you $5 over the course of the next year😆!). Once it is approved, you will be able to download the latest 1.18.1 version [here](https://www.curseforge.com/minecraft/mc-mods/fiblib). In the meantime, a 1.18.1 jar is also available on my [fork repository](https://github.com/Draylar/FibLib/releases).

**Comment by MSandro** [comment]
very nice, thank you
will the 1.17.1 version be available there too?

**Comment by 0gp** [comment]
Thank you very much, the Project is available now.
But no 1.17.1 Version? ☹️

**Comment by skyfallwastaken** [comment]
Nice work @Draylar, but AFAIK the mod should be classified as a library?

**Comment by MJeannette97** [comment]
Why is just the 1.18.1 Version available in CF?
It would be very nice if you could add the 1.17.1 Version too.

Thanks

**Comment by Draylar** [comment]
Just released 1.17.1 and re-marked the project as a library, thanks for the reminder :)

**Comment by MSandro** [comment]
Thanks a lot.

**Comment by MSandro** [comment]
will 1.18.2 be uploaded?

**Comment by 0gp** [comment]
on Github here 1.3.1-1.18.2 was released, but why was it not uploaded to CurseForge?

**Comment by Draylar** [comment]
Just pushed a 1.18.2 binary to CurseForge - let me know if you have any problems using it!

Link: https://www.curseforge.com/minecraft/mc-mods/fiblib/files/3803672 (pending upload)
